### ISSUE TITLE
Only works clientside

### ISSUE THREAD

**Issue by GambetTV** [eadorin/about-face#33] opened 2020-09-28 04:32 UTC
This seems to work fine on the computer moving the tokens, but it doesn't update any of the other players. So tokens will move around but never adjust their facing indicator. The only time it does is if you refresh the window, which it's hard to justify hitting F5 every time someone moves a token.

**Comment by Bryn1701** [comment] 2020-10-28 03:55
Great module, but yes I find this annoying also. I thought I could get this to work, but to no avail.

**Comment by edzillion** [comment] 2020-11-30 23:36
Ok clients and GM should be synchronised in latest. Can you test?

**Comment by Bryn1701** [comment] 2020-12-01 11:16
I can confirm it is now synchronising with both the GM and the Player. What weird anomaly I found, is when two players are connected without the GM(on the Forge) the players rotation and arrows do not synch.

**Comment by edzillion** [comment] 2020-12-01 14:51
Interesting you mention this because the technique I used to make it network friendly was for the GM to watch for changes and then update all clients. 

How often would you be playing and not have a GM though? Not sure about the urgency of this issue.

**Comment by edzillion** [comment] 2020-12-02 21:43
If there's a feature request for being able to use without any GM please add it. I am gonna close this for now.

**Closed by edzillion** 2020-12-02 21:43 UTC
